# Generated by Django 4.2.5 on 2023-09-19 09:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Crust',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.IntegerField(choices=[(1, 'SMALL'), (2, 'MEDIUM'), (3, 'LARGE'), (4, 'XLARGE')])),
                ('price', models.DecimalField(decimal_places=2, max_digits=7)),
            ],
            options={
                'unique_together': {('size', 'price')},
            },
        ),
        migrations.CreateModel(
            name='Topping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phonenumber', models.CharField(max_length=20)),
                ('crust', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pizza.crust')),
                ('topping', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pizza.topping')),
            ],
        ),
    ]
