# Generated by Django 4.2.5 on 2023-09-20 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizza', '0002_ordermessageconfig'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crust',
            name='size',
            field=models.CharField(choices=[('small', 'SMALL'), ('medium', 'MEDIUM'), ('large', 'LARGE'), ('extra large', 'XLARGE')], max_length=15),
        ),
    ]
