# Generated by Django 4.2.5 on 2023-09-20 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizza', '0004_alter_crust_size'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='phonenumber',
        ),
        migrations.AlterField(
            model_name='crust',
            name='size',
            field=models.IntegerField(choices=[(1, 'small'), (2, 'medium'), (3, 'large'), (4, 'extra large')]),
        ),
    ]
