# Generated by Django 4.2.5 on 2023-09-20 11:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pizza', '0005_remove_order_phonenumber_alter_crust_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='topping',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='pizza.topping'),
        ),
    ]
