# Generated by Django 4.2.5 on 2023-09-20 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizza', '0006_alter_order_topping'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='draft',
            field=models.BooleanField(default=False),
        ),
    ]
