# Generated by Django 4.2.5 on 2023-09-20 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizza', '0007_order_draft'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='draft',
            field=models.BooleanField(default=True),
        ),
    ]
